/** Dropdown options extracted from waterloo-enrolement-2024.csv */

export const FIELD_OPTIONS = {
  fiscal_year: [
    "2016/17", "2017/18", "2018/19", "2019/20",
    "2020/21", "2021/22", "2022/23", "2023/24",
  ],
  term_type: ["Fall term", "Spring term", "Winter term"],
  career: ["Graduate", "Undergraduate"],
  program_level: [
    "Bachelors", "Diploma", "Doctoral", "Masters", "Non-Degree", "Qualifying",
  ],
  study_year: ["1", "2", "3", "4", "5", "D", "M", "N"],
  campus: [
    "Conrad Grebel University College", "Online", "Online - Renison",
    "Renison University College", "St. Jerome's University",
    "University of Waterloo",
  ],
  faculty_group: [
    "ARTS", "CFM", "ENG", "ENV", "HEA", "MATH", "REN", "SCI", "SE", "SFM", "THL",
  ],
  program_grouping: [
    "Accounting", "Accounting and Financial Management", "Actuarial Science",
    "Aging, Health and Well-Being", "Anthropology", "Applied Economics",
    "Applied Language Studies", "Applied Mathematics", "Arabic Language",
    "Architectural Engineering", "Architecture", "Arts", "Arts and Business",
    "Biochemistry", "Biology", "Biomedical Engineering", "Biomedical Sciences",
    "Biotechnology/Chartered Professional Accountancy",
    "Business Administration and Computer Science Double Degree",
    "Business Administration and Mathematics Double Degree",
    "Business and Entrepreneurship", "Business, Entrepreneurship and Technology",
    "Catholic Thought", "Chemical Engineering", "Chemical Physics", "Chemistry",
    "Chinese Language", "Church Music and Worship", "Civil Engineering",
    "Classical Studies", "Climate Change", "Climate Risk Management",
    "Combinatorics and Optimization", "Computational Mathematics",
    "Computational Science", "Computer Engineering", "Computer Science",
    "Computing and Financial Management", "Data Science", "Development Practice",
    "Digital Experience Innovation", "Drama", "Earth Sciences",
    "East Asian Studies", "Economics", "Electrical Engineering",
    "Electrical and Computer Engineering", "Engineering",
    "English Language and Literature", "Environment", "Environment and Business",
    "Environment and Resource Studies", "Environmental Engineering",
    "Environmental Science", "Environmental Studies",
    "Financial Analysis and Risk Management", "Fine Arts", "French",
    "Gender & Social Justice", "Geochemistry", "Geography",
    "Geography and Aviation", "Geography and Environmental Management",
    "Geological Engineering", "Geomatics", "German", "German Language",
    "Gerontology", "Global Business and Digital Arts", "Global Governance",
    "Health Evaluation", "Health Informatics", "Health Promotion",
    "Health Sciences", "Health Studies", "History", "Human Resources Management",
    "Independent Studies", "Indigenous Studies",
    "Information Technology Management", "International Development",
    "Kinesiology", "Knowledge Integration", "Korean Language", "Legal Studies",
    "Life Physics", "Life Sciences", "Local Economic Development",
    "Management Engineering", "Management Sciences", "Management Studies",
    "Materials and Nanosciences", "Mathematical Finance", "Mathematical Physics",
    "Mathematical Studies", "Mathematics", "Mathematics Teaching",
    "Mathematics/Business Administration",
    "Mathematics/Chartered Professional Accountancy",
    "Mathematics/Financial Analysis and Risk Management", "Mathematics/Teaching",
    "Mechanical Engineering", "Mechatronics Engineering", "Medicinal Chemistry",
    "Medieval Studies", "Music", "Nanotechnology Engineering", "Optometry",
    "Peace and Conflict Studies", "Pharmacy", "Philosophy", "Physics",
    "Physics and Astronomy", "Planning", "Political Science", "Psychology",
    "Public Health", "Public Health and Health Systems",
    "Public Issues Anthropology", "Public Service", "Pure Mathematics",
    "Quantitative Finance", "Recreation and Business",
    "Recreation and Leisure Studies", "Recreation and Sport Business",
    "Religious Studies", "Science", "Science and Aviation", "Science and Business",
    "Sexuality, Marriage and Family", "Social Development Studies", "Social Work",
    "Sociology", "Software Engineering", "Spanish", "Speech Communication",
    "Statistics", "Sustainability Management", "Systems Design Engineering",
    "Taxation", "Theological Studies", "Therapeutic Recreation", "UGOL", "UGSA",
    "Vision Science", "Work and Health",
  ],
  coop_regular: ["Co-op", "Regular"],
  work_term: ["Academic Term", "Work Term"],
  attendance: ["Full-Time", "Part-Time", "Unknown Attendance"],
  visa_status: ["Canadian", "Canadian Permanent Resident", "International"],
};

export const FIELD_LABELS = {
  fiscal_year: "Fiscal Year",
  term_type: "Term Type",
  career: "Career",
  program_level: "Program Level",
  study_year: "Study Year",
  campus: "Campus",
  faculty_group: "Faculty Group",
  program_grouping: "Program Grouping",
  coop_regular: "Co-op / Regular",
  work_term: "Work Term",
  attendance: "Attendance",
  visa_status: "Visa Status",
};

export const DEFAULT_PARAMS = {
  fiscal_year: ["2023/24"],
  term_type: ["Fall term"],
  career: ["Undergraduate"],
  program_level: ["Bachelors"],
  study_year: ["3"],
  campus: ["University of Waterloo"],
  faculty_group: ["MATH"],
  program_grouping: ["Computer Science"],
  coop_regular: ["Co-op"],
  work_term: ["Academic Term"],
  attendance: ["Full-Time"],
  visa_status: ["Canadian"],
};
